replicaCount: 1

image:
  repository: cortex/cortex-priority-engine
  tag: dev
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
