apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex-envoy-config
  namespace: cortex-system
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - name: listener_0
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 10000
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: ingress_http
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: backend
                          domains: ["*"]
                          routes:
                            - match:
                                prefix: "/"
                              route:
                                cluster: cortex_graph
                    http_filters:
                      - name: envoy.filters.http.ext_authz
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                          transport_api_version: V3
                          grpc_service:
                            envoy_grpc:
                              cluster_name: cortex_gateway
                            timeout: 0.25s
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
        - name: cortex_gateway
          type: STRICT_DNS
          connect_timeout: 0.5s
          http2_protocol_options: {}
          load_assignment:
            cluster_name: cortex_gateway
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: cortex-gateway.cortex-system.svc.cluster.local
                          port_value: 9001
        - name: cortex_graph
          type: STRICT_DNS
          connect_timeout: 0.5s
          load_assignment:
            cluster_name: cortex_graph
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: cortex-graph.cortex-system.svc.cluster.local
                          port_value: 8080
    admin:
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
