"use client";
import { useEffect, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { IdentityGraph } from "@/components/identity-graph";
import { IncidentRoomPanel } from "@/components/incident-room-panel";
import { NodeComparePanel } from "@/components/node-compare-panel";
import { NodeEvolutionPanel } from "@/components/node-evolution-panel";

type DeepSearchRecord={id:string;label:string;type:string;category:"machine"|"resource"|"identity"|"agent"|"node";status:"healthy"|"degraded"|"unreachable"|"unknown";relationCount:number;attackPathCount:number;alerts:number;privilegeScore:number;resourcePressure:number;blastRadiusScore:number;driftScore:number;kerberosDelegationRisk:number;sensitiveGroupAffinity:number;tierZeroExposure:boolean;focusAreas:string[];riskBand:"low"|"medium"|"high"|"critical";healthLatency:number|null;searchText:string};
type SearchPayload={generatedAt:string;total:number;tierZeroAssets?:string[];records:DeepSearchRecord[]};
type SortMode="privilege_desc"|"resource_desc"|"blast_desc"|"drift_desc"|"kerberos_desc"|"relations_desc"|"alerts_desc"|"alpha_asc";
type CategoryFilter="all"|DeepSearchRecord["category"];
type RiskFilter="all"|DeepSearchRecord["riskBand"];
type StatusFilter="all"|DeepSearchRecord["status"];
type FocusFilter="all"|"tier0"|"attack_path"|"blast_radius"|"ad_drift"|"kerberos"|"sensitive_group";
type SavedPreset={name:string;query:string;category:CategoryFilter;risk:RiskFilter;status:StatusFilter;focus:FocusFilter;sort:SortMode};
type IncidentRoom={name:string;query:string;selectedId:string|null;compareIds:string[];favorites:string[];notesByNode:Record<string,string>;tagsByNode:Record<string,string[]>};

const K={presets:"cortex-console.deep-search.saved-presets",state:"cortex-console.deep-search.state",recent:"cortex-console.deep-search.recent-queries",favorites:"cortex-console.deep-search.favorites",compare:"cortex-console.deep-search.compare",notes:"cortex-console.deep-search.notes",tags:"cortex-console.deep-search.tags",rooms:"cortex-console.deep-search.incident-rooms"};
const SERVER_SCOPE="deep-search";
const PRESETS=[{label:"Tier 0 / admin",query:"admin tier0 domain",sort:"privilege_desc" as SortMode},{label:"Machines degradees",query:"",category:"machine" as CategoryFilter,status:"degraded" as StatusFilter},{label:"Attack paths",query:"",sort:"privilege_desc" as SortMode,risk:"high" as RiskFilter},{label:"Agents critiques",query:"",category:"agent" as CategoryFilter,risk:"critical" as RiskFilter},{label:"Resources exposees",query:"",category:"resource" as CategoryFilter,sort:"resource_desc" as SortMode},{label:"Blast radius",query:"",focus:"blast_radius" as FocusFilter,sort:"blast_desc" as SortMode},{label:"Kerberos / delegation",query:"",focus:"kerberos" as FocusFilter,sort:"kerberos_desc" as SortMode},{label:"AD drift",query:"",focus:"ad_drift" as FocusFilter,sort:"drift_desc" as SortMode},{label:"Sensitive groups",query:"",focus:"sensitive_group" as FocusFilter,sort:"privilege_desc" as SortMode}];

function parseStructuredQuery(input:string){const tokens=input.trim().split(/\s+/).filter(Boolean);const clauses:Record<string,string>={};const freeTerms:string[]=[];for(const token of tokens){const i=token.indexOf(":");if(i>0){const k=token.slice(0,i).toLowerCase();const v=token.slice(i+1);if(v){clauses[k]=v;continue;}}freeTerms.push(token);}return{clauses,freeText:freeTerms.join(" ").toLowerCase()};}
async function loadSearch():Promise<SearchPayload>{const r=await fetch("/api/search/deep",{cache:"no-store"});if(!r.ok)throw new Error("deep_search_failed");return r.json();}
function barColor(score:number){if(score>=80)return"bg-red-500";if(score>=60)return"bg-orange-500";if(score>=35)return"bg-amber-500";return"bg-emerald-500";}
function lsGet<T>(key:string,fallback:T){try{const raw=window.localStorage.getItem(key);return raw?(JSON.parse(raw) as T):fallback;}catch{return fallback;}}
function lsSet(key:string,value:unknown){window.localStorage.setItem(key,JSON.stringify(value));}

export function DeepSearchWorkbench(){
 const [query,setQuery]=useState("");const [category,setCategory]=useState<CategoryFilter>("all");const [risk,setRisk]=useState<RiskFilter>("all");const [status,setStatus]=useState<StatusFilter>("all");const [focus,setFocus]=useState<FocusFilter>("all");const [sort,setSort]=useState<SortMode>("privilege_desc");const [selectedId,setSelectedId]=useState<string|null>(null);const [savedPresets,setSavedPresets]=useState<SavedPreset[]>([]);const [presetName,setPresetName]=useState("");const [recentQueries,setRecentQueries]=useState<string[]>([]);const [favorites,setFavorites]=useState<string[]>([]);const [compareIds,setCompareIds]=useState<string[]>([]);const [notesByNode,setNotesByNode]=useState<Record<string,string>>({});const [tagsByNode,setTagsByNode]=useState<Record<string,string[]>>({});const [tagInput,setTagInput]=useState("");const [incidentRooms,setIncidentRooms]=useState<IncidentRoom[]>([]);
 const {data}=useQuery({queryKey:["deep-search"],queryFn:loadSearch,refetchInterval:8000});const records=data?.records??[];
 const filtered=useMemo(()=>{const {clauses,freeText}=parseStructuredQuery(query);const ec=(clauses.category||clauses.type) as CategoryFilter|undefined;const er=clauses.risk as RiskFilter|undefined;const es=clauses.status as StatusFilter|undefined;const ef=clauses.focus as FocusFilter|undefined;const eo=clauses.sort as SortMode|undefined;const minPrivilege=Number(clauses.minpriv??"");const minBlast=Number(clauses.minblast??"");const minDrift=Number(clauses.mindrift??"");const minKerb=Number(clauses.minkerb??"");const t0=clauses.tier0==="true";return [...records.filter((record)=>{if(freeText&&!record.searchText.includes(freeText))return false;const c=ec&&ec!=="all"?ec:category;const r=er&&er!=="all"?er:risk;const s=es&&es!=="all"?es:status;const f=ef&&ef!=="all"?ef:focus;if(c!=="all"&&record.category!==c)return false;if(r!=="all"&&record.riskBand!==r)return false;if(s!=="all"&&record.status!==s)return false;if(f!=="all"&&!record.focusAreas.includes(f))return false;if(!Number.isNaN(minPrivilege)&&record.privilegeScore<minPrivilege)return false;if(!Number.isNaN(minBlast)&&record.blastRadiusScore<minBlast)return false;if(!Number.isNaN(minDrift)&&record.driftScore<minDrift)return false;if(!Number.isNaN(minKerb)&&record.kerberosDelegationRisk<minKerb)return false;if(t0&&!record.tierZeroExposure)return false;return true;})].sort((a,b)=>{switch(eo??sort){case"resource_desc":return b.resourcePressure-a.resourcePressure;case"blast_desc":return b.blastRadiusScore-a.blastRadiusScore;case"drift_desc":return b.driftScore-a.driftScore;case"kerberos_desc":return b.kerberosDelegationRisk-a.kerberosDelegationRisk;case"relations_desc":return b.relationCount-a.relationCount;case"alerts_desc":return b.alerts-a.alerts;case"alpha_asc":return a.label.localeCompare(b.label);default:return b.privilegeScore-a.privilegeScore;}});},[records,query,category,risk,status,focus,sort]);
 const selected=filtered.find((r)=>r.id===selectedId)??filtered[0]??records[0]??null;const compareNodes=records.filter((r)=>compareIds.includes(r.id));const favoriteNodes=records.filter((r)=>favorites.includes(r.id));const selectedNote=selected?notesByNode[selected.id]??"":"";const selectedTags=selected?tagsByNode[selected.id]??[]:[];
 useEffect(()=>{let cancelled=false;void fetch(`/api/operator-state?scope=${SERVER_SCOPE}`,{cache:"no-store"}).then(async(r)=>r.ok?r.json():null).then((payload:Partial<{savedPresets:SavedPreset[];recentQueries:string[];favorites:string[];compareIds:string[];notesByNode:Record<string,string>;tagsByNode:Record<string,string[]>;incidentRooms:IncidentRoom[];state:{query?:string;category?:CategoryFilter;risk?:RiskFilter;status?:StatusFilter;focus?:FocusFilter;sort?:SortMode;selectedId?:string|null}}> | null)=>{if(cancelled||!payload)return;if(payload.savedPresets)setSavedPresets(payload.savedPresets);if(payload.recentQueries)setRecentQueries(payload.recentQueries);if(payload.favorites)setFavorites(payload.favorites);if(payload.compareIds)setCompareIds(payload.compareIds);if(payload.notesByNode)setNotesByNode(payload.notesByNode);if(payload.tagsByNode)setTagsByNode(payload.tagsByNode);if(payload.incidentRooms)setIncidentRooms(payload.incidentRooms);if(payload.state){if(payload.state.query!==undefined)setQuery(payload.state.query);if(payload.state.category)setCategory(payload.state.category);if(payload.state.risk)setRisk(payload.state.risk);if(payload.state.status)setStatus(payload.state.status);if(payload.state.focus)setFocus(payload.state.focus);if(payload.state.sort)setSort(payload.state.sort);if(payload.state.selectedId!==undefined)setSelectedId(payload.state.selectedId);}}).catch(()=>undefined);setSavedPresets(lsGet(K.presets,[] as SavedPreset[]));setRecentQueries(lsGet(K.recent,[] as string[]));setFavorites(lsGet(K.favorites,[] as string[]));setCompareIds(lsGet(K.compare,[] as string[]));setNotesByNode(lsGet(K.notes,{} as Record<string,string>));setTagsByNode(lsGet(K.tags,{} as Record<string,string[]>));setIncidentRooms(lsGet(K.rooms,[] as IncidentRoom[]));const state=lsGet(K.state,{} as Partial<{query:string;category:CategoryFilter;risk:RiskFilter;status:StatusFilter;focus:FocusFilter;sort:SortMode;selectedId:string|null}>);if(state.query!==undefined)setQuery(state.query);if(state.category)setCategory(state.category);if(state.risk)setRisk(state.risk);if(state.status)setStatus(state.status);if(state.focus)setFocus(state.focus);if(state.sort)setSort(state.sort);if(state.selectedId!==undefined)setSelectedId(state.selectedId);return()=>{cancelled=true;};},[]);
 useEffect(()=>{lsSet(K.state,{query,category,risk,status,focus,sort,selectedId});},[query,category,risk,status,focus,sort,selectedId]);
 useEffect(()=>{const controller=new AbortController();void fetch(`/api/operator-state?scope=${SERVER_SCOPE}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({savedPresets,recentQueries,favorites,compareIds,notesByNode,tagsByNode,incidentRooms,state:{query,category,risk,status,focus,sort,selectedId}}),signal:controller.signal}).catch(()=>undefined);return()=>controller.abort();},[savedPresets,recentQueries,favorites,compareIds,notesByNode,tagsByNode,incidentRooms,query,category,risk,status,focus,sort,selectedId]);
 const applyPreset=(preset:{query:string;category?:CategoryFilter;risk?:RiskFilter;status?:StatusFilter;focus?:FocusFilter;sort?:SortMode;})=>{setQuery(preset.query);setCategory(preset.category??"all");setRisk(preset.risk??"all");setStatus(preset.status??"all");setFocus(preset.focus??"all");setSort(preset.sort??"privilege_desc");};
 const saveCurrentPreset=()=>{const name=presetName.trim();if(!name)return;const next=[{name,query,category,risk,status,focus,sort},...savedPresets.filter((p)=>p.name!==name)].slice(0,8);setSavedPresets(next);setPresetName("");lsSet(K.presets,next);};
 const removePreset=(name:string)=>{const next=savedPresets.filter((p)=>p.name!==name);setSavedPresets(next);lsSet(K.presets,next);};
 const rememberQuery=(value:string)=>{const normalized=value.trim();if(!normalized)return;const next=[normalized,...recentQueries.filter((i)=>i!==normalized)].slice(0,10);setRecentQueries(next);lsSet(K.recent,next);};
 const toggleFavorite=(id:string)=>{const next=favorites.includes(id)?favorites.filter((i)=>i!==id):[id,...favorites].slice(0,12);setFavorites(next);lsSet(K.favorites,next);};
 const toggleCompare=(id:string)=>{const next=compareIds.includes(id)?compareIds.filter((i)=>i!==id):[...compareIds,id].slice(0,3);setCompareIds(next);lsSet(K.compare,next);};
 const updateSelectedNote=(value:string)=>{if(!selected)return;const next={...notesByNode,[selected.id]:value};setNotesByNode(next);lsSet(K.notes,next);};
 const addTagToSelected=()=>{if(!selected)return;const value=tagInput.trim();if(!value)return;const next={...tagsByNode,[selected.id]:[...new Set([...(tagsByNode[selected.id]??[]),value])].slice(0,12)};setTagsByNode(next);setTagInput("");lsSet(K.tags,next);};
 const removeTagFromSelected=(value:string)=>{if(!selected)return;const next={...tagsByNode,[selected.id]:(tagsByNode[selected.id]??[]).filter((i)=>i!==value)};setTagsByNode(next);lsSet(K.tags,next);};
 const saveIncidentRoom=(name:string)=>{const next=[{name,query,selectedId,compareIds,favorites,notesByNode,tagsByNode},...incidentRooms.filter((r)=>r.name!==name)].slice(0,12);setIncidentRooms(next);lsSet(K.rooms,next);};
 const loadIncidentRoom=(name:string)=>{const room=incidentRooms.find((r)=>r.name===name);if(!room)return;setQuery(room.query);setSelectedId(room.selectedId);setCompareIds(room.compareIds);setFavorites(room.favorites);setNotesByNode(room.notesByNode);setTagsByNode(room.tagsByNode);lsSet(K.compare,room.compareIds);lsSet(K.favorites,room.favorites);lsSet(K.notes,room.notesByNode);lsSet(K.tags,room.tagsByNode);};
 const deleteIncidentRoom=(name:string)=>{const next=incidentRooms.filter((r)=>r.name!==name);setIncidentRooms(next);lsSet(K.rooms,next);};
 const exportLocalState=()=>{const payload={savedPresets,recentQueries,favorites,compareIds,notesByNode,tagsByNode,incidentRooms,state:{query,category,risk,status,focus,sort,selectedId}};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="cortex-console-local-search.json";link.click();URL.revokeObjectURL(url);};
 const importLocalState=async(file:File|null)=>{if(!file)return;const parsed=JSON.parse(await file.text()) as Partial<{savedPresets:SavedPreset[];recentQueries:string[];favorites:string[];compareIds:string[];notesByNode:Record<string,string>;tagsByNode:Record<string,string[]>;incidentRooms:IncidentRoom[];state:{query?:string;category?:CategoryFilter;risk?:RiskFilter;status?:StatusFilter;focus?:FocusFilter;sort?:SortMode;selectedId?:string|null;};}>;if(parsed.savedPresets){setSavedPresets(parsed.savedPresets);lsSet(K.presets,parsed.savedPresets);}if(parsed.recentQueries){setRecentQueries(parsed.recentQueries);lsSet(K.recent,parsed.recentQueries);}if(parsed.favorites){setFavorites(parsed.favorites);lsSet(K.favorites,parsed.favorites);}if(parsed.compareIds){setCompareIds(parsed.compareIds);lsSet(K.compare,parsed.compareIds);}if(parsed.notesByNode){setNotesByNode(parsed.notesByNode);lsSet(K.notes,parsed.notesByNode);}if(parsed.tagsByNode){setTagsByNode(parsed.tagsByNode);lsSet(K.tags,parsed.tagsByNode);}if(parsed.incidentRooms){setIncidentRooms(parsed.incidentRooms);lsSet(K.rooms,parsed.incidentRooms);}if(parsed.state){if(parsed.state.query!==undefined)setQuery(parsed.state.query);if(parsed.state.category)setCategory(parsed.state.category);if(parsed.state.risk)setRisk(parsed.state.risk);if(parsed.state.status)setStatus(parsed.state.status);if(parsed.state.focus)setFocus(parsed.state.focus);if(parsed.state.sort)setSort(parsed.state.sort);if(parsed.state.selectedId!==undefined)setSelectedId(parsed.state.selectedId);lsSet(K.state,parsed.state);}};

 return <div className="space-y-6">
  <section className="rounded-3xl border bg-panel/80 p-4 shadow-panel">
   <div className="flex flex-wrap items-start justify-between gap-4">
    <div>
     <h2 className="text-sm font-semibold uppercase tracking-[0.2em] text-muted">Moteur de recherche profond</h2>
     <p className="mt-1 text-sm text-muted">Trie les machines, ressources, noeuds et identites par privilege, pression, alertes et densite de relations.</p>
     <p className="mt-2 font-mono text-[11px] uppercase tracking-[0.18em] text-muted">Syntaxe: `type:machine risk:critical focus:kerberos minpriv:70 tier0:true`</p>
    </div>
    <div className="rounded-full border border-border/70 px-3 py-1 font-mono text-xs text-muted">{filtered.length}/{records.length} resultats</div>
   </div>
   <div className="mt-4 grid gap-3 xl:grid-cols-[1.2fr_repeat(5,minmax(0,0.5fr))]">
    <input value={query} onChange={(e)=>setQuery(e.target.value)} onBlur={(e)=>rememberQuery(e.target.value)} placeholder="Recherche libre: admin, machine, resource, tier0, node..." className="rounded-2xl border border-border/70 bg-background/45 px-4 py-3 text-sm text-ink outline-none" />
    <select value={category} onChange={(e)=>setCategory(e.target.value as CategoryFilter)} className="rounded-2xl border border-border/70 bg-background/45 px-3 py-3 text-sm text-ink outline-none"><option value="all">Toutes categories</option><option value="machine">Machines</option><option value="resource">Ressources</option><option value="identity">Identites</option><option value="agent">Agents</option><option value="node">Noeuds</option></select>
    <select value={risk} onChange={(e)=>setRisk(e.target.value as RiskFilter)} className="rounded-2xl border border-border/70 bg-background/45 px-3 py-3 text-sm text-ink outline-none"><option value="all">Tous risques</option><option value="critical">Critique</option><option value="high">Haut</option><option value="medium">Moyen</option><option value="low">Bas</option></select>
    <select value={status} onChange={(e)=>setStatus(e.target.value as StatusFilter)} className="rounded-2xl border border-border/70 bg-background/45 px-3 py-3 text-sm text-ink outline-none"><option value="all">Tous statuts</option><option value="healthy">Healthy</option><option value="degraded">Degraded</option><option value="unreachable">Unreachable</option><option value="unknown">Unknown</option></select>
    <select value={focus} onChange={(e)=>setFocus(e.target.value as FocusFilter)} className="rounded-2xl border border-border/70 bg-background/45 px-3 py-3 text-sm text-ink outline-none"><option value="all">Tous focus</option><option value="tier0">Tier 0</option><option value="attack_path">Attack path</option><option value="blast_radius">Blast radius</option><option value="ad_drift">AD drift</option><option value="kerberos">Kerberos</option><option value="sensitive_group">Sensitive groups</option></select>
    <select value={sort} onChange={(e)=>setSort(e.target.value as SortMode)} className="rounded-2xl border border-border/70 bg-background/45 px-3 py-3 text-sm text-ink outline-none"><option value="privilege_desc">Privilege</option><option value="resource_desc">Ressources</option><option value="blast_desc">Blast radius</option><option value="drift_desc">AD drift</option><option value="kerberos_desc">Kerberos</option><option value="relations_desc">Relations</option><option value="alerts_desc">Alertes</option><option value="alpha_asc">Alphabetique</option></select>
   </div>
   <div className="mt-4 flex flex-wrap gap-2">{PRESETS.map((preset)=><button key={preset.label} type="button" onClick={()=>applyPreset(preset)} className="rounded-full border border-border/70 bg-background/40 px-3 py-2 text-xs font-mono text-muted hover:border-cyan-500/40 hover:text-ink">{preset.label}</button>)}</div>
   <div className="mt-4 grid gap-3 md:grid-cols-[1fr_auto]"><input value={presetName} onChange={(e)=>setPresetName(e.target.value)} placeholder="Nom du preset operateur" className="rounded-2xl border border-border/70 bg-background/45 px-4 py-3 text-sm text-ink outline-none" /><button type="button" onClick={saveCurrentPreset} className="rounded-2xl border border-cyan-400/50 bg-cyan-400/10 px-4 py-3 text-sm font-semibold text-cyan-100">Sauvegarder</button></div>
   {savedPresets.length?<div className="mt-4 flex flex-wrap gap-2">{savedPresets.map((preset)=><div key={preset.name} className="flex items-center gap-2 rounded-full border border-border/70 bg-background/40 px-3 py-2"><button type="button" onClick={()=>applyPreset(preset)} className="text-xs font-mono text-muted hover:text-ink">{preset.name}</button><button type="button" onClick={()=>removePreset(preset.name)} className="font-mono text-xs text-red-300">x</button></div>)}</div>:null}
   {recentQueries.length?<div className="mt-4"><div className="mb-2 font-mono text-[11px] uppercase tracking-[0.2em] text-muted">Historique local</div><div className="flex flex-wrap gap-2">{recentQueries.map((item)=><button key={item} type="button" onClick={()=>setQuery(item)} className="rounded-full border border-border/70 bg-background/40 px-3 py-2 text-xs font-mono text-muted hover:border-cyan-500/40 hover:text-ink">{item}</button>)}</div></div>:null}
   <div className="mt-4 flex flex-wrap gap-3"><button type="button" onClick={exportLocalState} className="rounded-2xl border border-border/70 bg-background/40 px-4 py-3 text-sm font-semibold text-ink">Export JSON local</button><label className="rounded-2xl border border-border/70 bg-background/40 px-4 py-3 text-sm font-semibold text-ink">Import JSON local<input type="file" accept="application/json" className="hidden" onChange={(e)=>void importLocalState(e.target.files?.[0]??null)} /></label></div>
  </section>
  <IncidentRoomPanel onSave={saveIncidentRoom} rooms={incidentRooms} onLoad={loadIncidentRoom} onDelete={deleteIncidentRoom} />
  <section className="grid gap-6 xl:grid-cols-[0.92fr_1.08fr]">
   <div className="rounded-3xl border bg-panel/80 p-4 shadow-panel"><div className="mb-4 text-sm font-semibold uppercase tracking-[0.2em] text-muted">Resultats</div><div className="max-h-[42rem] space-y-3 overflow-auto pr-1">
    {filtered.map((record)=><button key={record.id} type="button" onClick={()=>setSelectedId(record.id)} className={`w-full rounded-2xl border p-4 text-left ${selected?.id===record.id?"border-cyan-400/60 bg-cyan-400/10":"border-border/70 bg-background/30"}`}>
      <div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-sm font-semibold text-ink">{record.label}</div><div className="mt-1 font-mono text-[11px] uppercase tracking-[0.2em] text-muted">{record.type} | {record.category} | {record.id}</div></div><div className="flex items-center gap-2"><span className="rounded-full border border-border/70 px-2 py-1 font-mono text-xs text-muted">{favorites.includes(record.id)?"fav":"node"}</span><span className="rounded-full border border-border/70 px-2 py-1 font-mono text-xs text-muted">{record.status}</span><span className="rounded-full border border-border/70 px-2 py-1 font-mono text-xs text-muted">{record.riskBand}</span></div></div>
      <div className="mt-4 grid gap-3 md:grid-cols-2">{[["Privilege",record.privilegeScore],["Pressure",record.resourcePressure],["Blast radius",record.blastRadiusScore],["AD drift",record.driftScore],["Kerberos",record.kerberosDelegationRisk]].map(([label,value])=><div key={String(label)}><div className="mb-1 flex justify-between font-mono text-[11px] uppercase tracking-[0.2em] text-muted"><span>{label}</span><span>{value}</span></div><div className="h-2 overflow-hidden rounded-full bg-background/60"><div className={`h-full ${barColor(Number(value))}`} style={{width:`${value}%`}} /></div></div>)}</div>
      <div className="mt-4 grid grid-cols-4 gap-2 font-mono text-xs text-muted"><span>alerts={record.alerts}</span><span>edges={record.relationCount}</span><span>paths={record.attackPathCount}</span><span>lat={record.healthLatency??"n/a"}</span></div>
      <div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={(e)=>{e.stopPropagation();toggleFavorite(record.id);}} className="rounded-full border border-border/70 px-2 py-1 font-mono text-[11px] uppercase tracking-[0.2em] text-muted">{favorites.includes(record.id)?"unfavorite":"favorite"}</button><button type="button" onClick={(e)=>{e.stopPropagation();toggleCompare(record.id);}} className="rounded-full border border-border/70 px-2 py-1 font-mono text-[11px] uppercase tracking-[0.2em] text-muted">{compareIds.includes(record.id)?"remove compare":"compare"}</button>{record.focusAreas.map((focusArea)=><span key={focusArea} className="rounded-full border border-border/70 px-2 py-1 font-mono text-[11px] uppercase tracking-[0.2em] text-muted">{focusArea}</span>)}{record.tierZeroExposure?<span className="rounded-full border border-red-500/40 bg-red-500/10 px-2 py-1 font-mono text-[11px] uppercase tracking-[0.2em] text-red-200">tier0 exposed</span>:null}</div>
    </button>)}
    {!filtered.length?<div className="rounded-2xl border border-dashed border-border/70 p-6 text-sm text-muted">Aucun resultat pour cette recherche.</div>:null}
   </div></div>
   <div className="space-y-6">
    <IdentityGraph highlightId={selected?.id??null} onNodeSelect={setSelectedId} />
    <div className="rounded-3xl border bg-panel/80 p-4 shadow-panel">
     <div className="text-sm font-semibold uppercase tracking-[0.2em] text-muted">Inspecteur</div>
     {selected?<div className="mt-4 space-y-4">
      <div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-border/70 bg-background/35 p-4"><div className="font-mono text-xs uppercase tracking-[0.2em] text-muted">Objet</div><div className="mt-2 text-lg font-semibold text-ink">{selected.label}</div><div className="mt-2 font-mono text-xs text-muted">{selected.id}</div></div><div className="rounded-2xl border border-border/70 bg-background/35 p-4"><div className="font-mono text-xs uppercase tracking-[0.2em] text-muted">Classe</div><div className="mt-2 text-lg font-semibold text-ink">{selected.category}</div><div className="mt-2 font-mono text-xs text-muted">{selected.type}</div></div></div>
      <pre className="overflow-auto rounded-2xl border border-border/70 bg-background/35 p-4 font-mono text-xs text-muted">{JSON.stringify(selected,null,2)}</pre>
      <div className="rounded-2xl border border-border/70 bg-background/35 p-4"><div className="font-mono text-xs uppercase tracking-[0.2em] text-muted">Notes privees</div><textarea value={selectedNote} onChange={(e)=>updateSelectedNote(e.target.value)} placeholder="Notes operateur locales pour ce noeud" className="mt-3 min-h-28 w-full rounded-xl border border-border/70 bg-background/45 px-3 py-3 text-sm text-ink outline-none" /></div>
      <div className="rounded-2xl border border-border/70 bg-background/35 p-4"><div className="font-mono text-xs uppercase tracking-[0.2em] text-muted">Tags locaux</div><div className="mt-3 grid gap-3 md:grid-cols-[1fr_auto]"><input value={tagInput} onChange={(e)=>setTagInput(e.target.value)} placeholder="Ajouter un tag local" className="rounded-xl border border-border/70 bg-background/45 px-3 py-3 text-sm text-ink outline-none" /><button type="button" onClick={addTagToSelected} className="rounded-xl border border-cyan-400/50 bg-cyan-400/10 px-4 py-3 text-sm font-semibold text-cyan-100">Ajouter</button></div><div className="mt-3 flex flex-wrap gap-2">{selectedTags.map((tag)=><button key={tag} type="button" onClick={()=>removeTagFromSelected(tag)} className="rounded-full border border-border/70 px-2 py-1 font-mono text-[11px] uppercase tracking-[0.2em] text-muted">{tag} x</button>)}{!selectedTags.length?<span className="font-mono text-xs text-muted">Aucun tag local</span>:null}</div></div>
     </div>:<div className="mt-4 rounded-2xl border border-dashed border-border/70 p-6 text-sm text-muted">Selectionnez un noeud pour voir ses details de privilege, charge et relations.</div>}
    </div>
    <NodeEvolutionPanel node={selected?{id:selected.id,label:selected.label,privilegeScore:selected.privilegeScore,blastRadiusScore:selected.blastRadiusScore,driftScore:selected.driftScore,kerberosDelegationRisk:selected.kerberosDelegationRisk,alerts:selected.alerts}:null} />
    <NodeComparePanel nodes={compareNodes.map((node)=>({id:node.id,label:node.label,type:node.type,category:node.category,privilegeScore:node.privilegeScore,blastRadiusScore:node.blastRadiusScore,driftScore:node.driftScore,kerberosDelegationRisk:node.kerberosDelegationRisk,alerts:node.alerts,riskBand:node.riskBand}))} />
    <div className="rounded-3xl border bg-panel/80 p-4 shadow-panel"><div className="text-sm font-semibold uppercase tracking-[0.2em] text-muted">Favoris locaux</div>{favoriteNodes.length?<div className="mt-4 flex flex-wrap gap-2">{favoriteNodes.map((node)=><button key={node.id} type="button" onClick={()=>setSelectedId(node.id)} className="rounded-full border border-border/70 bg-background/40 px-3 py-2 text-xs font-mono text-muted hover:text-ink">{node.label}</button>)}</div>:<div className="mt-4 rounded-2xl border border-dashed border-border/70 p-6 text-sm text-muted">Aucun favori local pour le moment.</div>}</div>
   </div>
  </section>
 </div>;
}
