apiVersion: v1
kind: Service
metadata:
  name: cortex-sentinel-machine
  namespace: cortex-system
  labels:
    app.kubernetes.io/name: cortex-sentinel-machine
    app.kubernetes.io/part-of: cortex
spec:
  selector:
    app.kubernetes.io/name: cortex-sentinel-machine
  ports:
    - name: grpc
      port: 50061
      targetPort: grpc
    - name: metrics
      port: 18080
      targetPort: metrics
