apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: cortex-system
  labels:
    app.kubernetes.io/name: cortex-sentinel-machine
    app.kubernetes.io/part-of: cortex

