apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-vault-internal
  namespace: vault-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: vault
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: vault-system
      ports:
        - protocol: TCP
          port: 8200
        - protocol: TCP
          port: 8201
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: vault-system
      ports:
        - protocol: TCP
          port: 8200
        - protocol: TCP
          port: 8201
